/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package survey.ui.panel;

import javax.swing.JOptionPane;
import survey.ui.panel.controller.ConsumptionPanelController;

/**
 *
 * @author rakib
 */
public class ConsumptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConsumptionPanel
     */
    private ConsumptionPanelController theController;
    public ConsumptionPanel() {
        initComponents();
        theController=new ConsumptionPanelController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        electriciyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        electricyTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totalElectriciy = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalUsagesElectriciy = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        naturalGasPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gasTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        totalGas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalUsageGas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        electriciyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Electricity"));

        electricyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sector", "Percentage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        electricyTable.setColumnSelectionAllowed(true);
        electricyTable.getTableHeader().setReorderingAllowed(false);
        electricyTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                electricyTableFocusLost(evt);
            }
        });
        electricyTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                electricyTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(electricyTable);
        electricyTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setText("Total:");

        totalElectriciy.setText("jLabel2");

        jLabel3.setText("<html>\n<center>\nTotal Annual Usage<br>\n(kWh/yr)\n</center>\n</html>");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalUsagesElectriciy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalUsagesElectriciyActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Consumption Percentage");

        javax.swing.GroupLayout electriciyPanelLayout = new javax.swing.GroupLayout(electriciyPanel);
        electriciyPanel.setLayout(electriciyPanelLayout);
        electriciyPanelLayout.setHorizontalGroup(
            electriciyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, electriciyPanelLayout.createSequentialGroup()
                .addGroup(electriciyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(electriciyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, electriciyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, electriciyPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(totalElectriciy)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, electriciyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(totalUsagesElectriciy, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        electriciyPanelLayout.setVerticalGroup(
            electriciyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, electriciyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(electriciyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(totalUsagesElectriciy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(electriciyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalElectriciy))
                .addGap(15, 15, 15))
        );

        naturalGasPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Fuels (Natural Gas/ Coal/ Saw Dust/ Others)"));

        gasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sector", "Percentage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gasTable.getTableHeader().setReorderingAllowed(false);
        gasTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gasTableFocusLost(evt);
            }
        });
        gasTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                gasTableInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        gasTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                gasTablePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(gasTable);
        gasTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel5.setText("Total:");

        totalGas.setText("jLabel2");

        jLabel7.setText("<html> <center> Total Annual Usage<br> (MMBtu/yr) </center> </html>");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        totalUsageGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalUsageGasActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Consumption Percentage");

        javax.swing.GroupLayout naturalGasPanelLayout = new javax.swing.GroupLayout(naturalGasPanel);
        naturalGasPanel.setLayout(naturalGasPanelLayout);
        naturalGasPanelLayout.setHorizontalGroup(
            naturalGasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, naturalGasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(naturalGasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, naturalGasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(totalUsageGas, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(naturalGasPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(totalGas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        naturalGasPanelLayout.setVerticalGroup(
            naturalGasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, naturalGasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(naturalGasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(totalUsageGas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(naturalGasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalGas))
                .addGap(23, 23, 23))
        );

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("jLabel2");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(electriciyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naturalGasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(electriciyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naturalGasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void totalUsagesElectriciyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalUsagesElectriciyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalUsagesElectriciyActionPerformed

    private void totalUsageGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalUsageGasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalUsageGasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        theController.okayButton();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void electricyTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_electricyTablePropertyChange
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Yeah");
        theController.tableChanged();
    }//GEN-LAST:event_electricyTablePropertyChange

    private void gasTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gasTablePropertyChange
        // TODO add your handling code here:
        theController.tableChanged();
    }//GEN-LAST:event_gasTablePropertyChange

    private void electricyTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_electricyTableFocusLost
        // TODO add your handling code here:
        theController.resetElectricityCellFocus();
    }//GEN-LAST:event_electricyTableFocusLost

    private void gasTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_gasTableInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_gasTableInputMethodTextChanged

    private void gasTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gasTableFocusLost
        // TODO add your handling code here:
        theController.resetGasCellFocus();
    }//GEN-LAST:event_gasTableFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel electriciyPanel;
    public javax.swing.JTable electricyTable;
    public javax.swing.JLabel errorLabel;
    public javax.swing.JTable gasTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel naturalGasPanel;
    public javax.swing.JLabel totalElectriciy;
    public javax.swing.JLabel totalGas;
    public javax.swing.JTextField totalUsageGas;
    public javax.swing.JTextField totalUsagesElectriciy;
    // End of variables declaration//GEN-END:variables
}
