/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package survey.ui.panel;
import survey.ui.panel.controller.ProjectNoController;
/**
 *
 * @author rakib
 */
public class EneregyProjectNoCollector extends javax.swing.JPanel {

    /**
     * Creates new form EneregyProjectNoCollector
     */
    ProjectNoController theController;
    public EneregyProjectNoCollector() {
        initComponents();
        theController=new ProjectNoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectNoButtonGroup = new javax.swing.ButtonGroup();
        lessFiveButton = new javax.swing.JToggleButton();
        fiveTenButton = new javax.swing.JToggleButton();
        greaterTenButton = new javax.swing.JToggleButton();
        label1 = new java.awt.Label();

        projectNoButtonGroup.add(lessFiveButton);
        lessFiveButton.setText("jToggleButton1");
        lessFiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessFiveButtonActionPerformed(evt);
            }
        });

        projectNoButtonGroup.add(fiveTenButton);
        fiveTenButton.setText("jToggleButton2");
        fiveTenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveTenButtonActionPerformed(evt);
            }
        });

        projectNoButtonGroup.add(greaterTenButton);
        greaterTenButton.setText("jToggleButton3");
        greaterTenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greaterTenButtonActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label1.setText("How many projects you have implemented to improve your energy efficiency in last 5 years?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lessFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(fiveTenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(483, 483, 483)
                .addComponent(greaterTenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(greaterTenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(fiveTenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lessFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void greaterTenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greaterTenButtonActionPerformed
        // TODO add your handling code here:
        theController.buttonClicked(theController.GREATER_TEN);
    }//GEN-LAST:event_greaterTenButtonActionPerformed

    private void fiveTenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveTenButtonActionPerformed
        // TODO add your handling code here:
         theController.buttonClicked(theController.FIVE_TO_TEN);
    }//GEN-LAST:event_fiveTenButtonActionPerformed

    private void lessFiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessFiveButtonActionPerformed
        // TODO add your handling code here:
         theController.buttonClicked(theController.LESS_FIVE);
    }//GEN-LAST:event_lessFiveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton fiveTenButton;
    public javax.swing.JToggleButton greaterTenButton;
    private java.awt.Label label1;
    public javax.swing.JToggleButton lessFiveButton;
    private javax.swing.ButtonGroup projectNoButtonGroup;
    // End of variables declaration//GEN-END:variables
}
